### PR TITLE
WADD BALI

### PR DESCRIPTION
**Pull request by BeniPrianto**
Finished

### CODE REVIEW

**Comment by BeniPrianto** [comment]
WADD BALI

**Comment by dushyants19** [comment]
Push to august2016, next time please. :)

**Comment by BeniPrianto** [comment]
sorry, I didn't correct. Next time I will push month active

**Comment by dushyants19** [comment]
WICT is rejected. Here is why:

- No Airport Boundary
- No Beacon
- Terminal not drawn

WADD is also rejected. Here is why: 

- Taxiways overlapping/not snapped
- Not aligned with WEDbing
- Buildings missing
- Incorrect border 
- No Holes for taxiways
- Many lines are not snapped

**Comment by BeniPrianto** [comment]
I will soon fix it. thank you for corrections.

**Pull request closed without merging**
