### PR TITLE
RKJM

### PR DESCRIPTION
**Pull request by adrinerDP**
#1864 
Image

### CODE REVIEW

**Comment by ItsW1ll** [comment]
why have you put an ILS hold round the entire airport??

**Comment by adrinerDP** [comment]
removed line

**Comment by ItsW1ll** [comment]
you shouldn't be making pull requests anyway. please email them to airports@liveflightapp.com

**Comment by adrinerDP** [comment]
@dushyants19 approved to do pull request.

**Comment by ItsW1ll** [comment]
right, okay i'll leave with you @dushyants19.

**Comment by dushyants19** [comment]
I cannot add it, here is why:

- Holes not cut for concrete taxiways on ASPHALT
- New Taxiway 2, 4 are not snapped at contact points
- New Taxiway 3 is not snapped with Taxiway 4
- Road and Taxiway not snapped

image


- Incorrect Runway Markings
- Incorrect Ramp Start Type for Spawns
- Incorrect Ramp Operation Type for Spawns

Nice work @adrinerDP

**Pull request closed without merging**
