### PR TITLE
RKPC

### PR DESCRIPTION
**Pull request by adrinerDP**
#2190 
One of the busiest routes in the world

### CODE REVIEW

**Comment by adrinerDP** [comment]
Any progress?

**Comment by dushyants19** [comment]
Reexport Properly with all groups visible,

Meanwhile:

- Avoid having 2 taxiways joined with the same line attribute 

image

**Comment by adrinerDP** [comment]
re exported and should I remove same line attributes?

**Comment by dushyants19** [comment]
@adrinerDP yes. Keep it on one of the 2 taxiways joining

**Comment by adrinerDP** [comment]
@dushyants19 fixed

**Comment by adrinerDP** [comment]
no progress?

**Comment by ewanfleming** [comment]
Patience...

**Comment by dushyants19** [comment]
- Incorrect Spawn Sizes

image


- Missing Gate Outlines
- Missing these circles

image

- Heavy Jets' equipment only for size E and above

image

Many other spawns have this issue as well

- Joining Taxiways with each other don't require so many nodes and they don't need to be snapped with lines either

image



- Incorrect Runway Markings for 13/31

**Comment by dushyants19** [comment]
#2190

**Pull request merged**
