### PR TITLE
SBBE-Val-de Cans intl airport

### PR DESCRIPTION
**Pull request by DarlanFernandes**
CITY:BELÉM
STATE:PARÁ
COUNTRY: BRAZIL

### CODE REVIEW

**Comment by dushyants19** [comment]
So this is a new airport not in the repo? @DarlanFernandes

**Comment by dushyants19** [comment]
Its in the repo, and I see you haven't changed anything, If you are willing to contribute and edit this airport. Please mail to `airports@liveflightapp.com`

**Comment by DarlanFernandes** [comment]
@dushyants19 
Because I have difficulties to request the international airport of my city for the Global Mode

**Comment by DarlanFernandes** [comment]
@dushyants19 But I already sent the airport to airports@liveflightapp.com

**Comment by dushyants19** [comment]
@DarlanFernandes you dont need to request it for it to be added. ALL Airports will be added, go tell your friends too. 

GLOBAL = ENTIRE GLOBE

**Pull request closed without merging**
