### PR TITLE
Invalid

### PR DESCRIPTION
**Pull request by cptchris**
Fixed Spawns, Added Military Pads.

### CODE REVIEW

**Comment by cptchris** [comment]
Any Progress?

**Comment by dushyants19** [comment]
Approved by Mortiz in 1801ff7

**Comment by dushyants19** [comment]
MIL pads missing
Spawns can be placed more with more order

image

**Comment by cptchris** [comment]
Were is the missing pads?

**Comment by dushyants19** [comment]
@cptchris check kilt's charts on #2143

**Comment by brunocr98** [comment]
This one either.

**Pull request closed without merging**
